[window]
opacity = 0.7  # 70% transparan
padding = { x = 10, y = 10 }
decorations = "full"
dynamic_title = true

[font]
normal = { family = "Noto Sans Mono", style = "Regular" }
bold = { family = "Noto Sans Mono", style = "Bold" }
italic = { family = "Noto Sans Mono", style = "Italic" }
size = 7

[colors]
primary = { background = "#040406", foreground = "#EBDBB2" }
cursor = { text = "#040406", cursor = "#EBDBB2" }

normal = { black = "#040406", red = "#EB3C42", green = "#A35659", yellow = "#AD7F81", blue = "#B3A2A3", magenta = "#EB3C42", cyan = "#AD7F81", white = "#EBDBB2" }

bright = { black = "#1a1a1a", red = "#ff5f5f", green = "#b86f6f", yellow = "#c28c8c", blue = "#ccb3b3", magenta = "#ff5f5f", cyan = "#c28c8c", white = "#f0e0d6" }

[selection]
save_to_clipboard = true
